config/routes.rb
Rails.application.routes.draw do
  resources :timetickets
  get 'timeticket/index'

  resources :fields
  get 'field/index'

  root to: 'gardens#index'

  resources :inventories
  resources :schedulers
  resources :gardens
  resources :bananas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server, at: '/cable'
end

app/models/scheduler.rb
class Scheduler < ApplicationRecord
  belongs_to :garden

  MAXMINUTES = 30 #seconds
  LATENCY = 0 #latency before first banana gets updated. used in ini

  #not needed scheduler.garden is available when there is a scheduler id in the garden table.
  # def findgarden
  #   self.garden= Gardens.where(scheduler_id == self.id)
  # end

  # after_save
  # after_initialize :enqueue, :assignticketstobananas
  # bugs ...

  after_create :assignticketstobananas, :enqueue

  def run
    puts "scheduler is runnig"
    enqueue
  end

  def assignticketstobananas
    bs = garden.bananas
      maxripe = Banana.maxripe
      bs.each do |b|
        # only call method at after_create and max 3 tickets will be spawned
        # unless b.ismaxripe and b.timetickets < b.maxripe
        howmanytickets = maxripe - b.ripeness
        newtime = inittime
        createtickets howmanytickets, newtime,
                    (Timeticket.create banana_id: b.id,
                                      time: newtime)
        # end
      end
    # end
  end
  def inittime
     Time.now + LATENCY.seconds + rand(MAXMINUTES).seconds
  end
  def randomnexttime time
     time + LATENCY.seconds + rand(MAXMINUTES).seconds
  end
  def createtickets count, time, ticket,
    atime = ticket.time
    bid = ticket.banana_id
    if count > 0
      count =- 1
      newtime = randomnexttime time
      createtickets count, newtime, (Timeticket.create banana_id: bid, time: newtime)
    end
  end



  # mit cable dann event firen sodass bananen farbe verändern und in datenbank geupdated werden.
  def enqueue
    puts "hello enqueue"

    # fire_overdues
    overdues = Timeticket.where('time <= ?', Time.now)
    overdues.each do |v|
      v.banana.nextripe
      v.destroy
    end
    queue = Timeticket.where('time > ?', Time.now).sort_by{|x| x.time}
    sleeptime = 0

    # live execution of ripeness++
    # queue.each do |ticket|
    #   sleeptime = ticket.time - Time.now
    #   #wait
    #   threads = []
    #   t= Thread.new do
    #     threads << []
    #     puts "#{t} sleep #{sleeptime}"
    #     if sleeptime > 3*60
    #       sleep sleeptime
    #     end
    #   end
    #   t.join
    #   puts threads
    #   t.kill
    #   ticket.banana.nextripe
    #   ticket.destroy
    # end



    #def fire
    # Thread.new do
    #   sleep sleeptime
    #   ticket.banana.nextripe
    #   ActionCable.server.broadcast 'grid_channel', content: "##{posx}-#{posy}"
    # end
    #end
  end
end

app/controllers/schedulers_controller.rb
class SchedulersController < ApplicationController
  before_action :set_scheduler, only: [:show, :edit, :update, :destroy]

  # GET /schedulers
  # GET /schedulers.json
  def index
    @schedulers = Scheduler.all
  end

  # GET /schedulers/1
  # GET /schedulers/1.json
  def show
  end

  # GET /schedulers/new
  def new
    @scheduler = Scheduler.new
  end

  # GET /schedulers/1/edit
  def edit
  end

  # POST /schedulers
  # POST /schedulers.json
  def create
    @scheduler = Scheduler.new(scheduler_params)

    respond_to do |format|
      if @scheduler.save
        format.html { redirect_to @scheduler, notice: 'Scheduler was successfully created.' }
        format.json { render :show, status: :created, location: @scheduler }
      else
        format.html { render :new }
        format.json { render json: @scheduler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedulers/1
  # PATCH/PUT /schedulers/1.json
  def update
    respond_to do |format|
      if @scheduler.update(scheduler_params)
        format.html { redirect_to @scheduler, notice: 'Scheduler was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduler }
      else
        format.html { render :edit }
        format.json { render json: @scheduler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedulers/1
  # DELETE /schedulers/1.json
  def destroy
    @scheduler.destroy
    respond_to do |format|
      format.html { redirect_to schedulers_url, notice: 'Scheduler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduler
      @scheduler = Scheduler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduler_params
      params.fetch(:scheduler, {})
    end
end

app/helpers/schedulers_helper.rb
module SchedulersHelper
end

app/views/schedulers/_form.html.erb
<%= form_with(model: scheduler, local: true) do |form| %>
  <% if scheduler.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scheduler.errors.count, "error") %> prohibited this scheduler from being saved:</h2>

      <ul>
      <% scheduler.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedulers/edit.html.erb
<h1>Editing Scheduler</h1>

<%= render 'form', scheduler: @scheduler %>

<%= link_to 'Show', @scheduler %> |
<%= link_to 'Back', schedulers_path %>

app/views/schedulers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedulers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedulers.each do |scheduler| %>
      <tr>
        <td><%= link_to 'Show', scheduler %></td>
        <td><%= link_to 'Edit', edit_scheduler_path(scheduler) %></td>
        <td><%= link_to 'Destroy', scheduler, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scheduler', new_scheduler_path %>

app/views/schedulers/new.html.erb
<h1>New Scheduler</h1>

<%= render 'form', scheduler: @scheduler %>

<%= link_to 'Back', schedulers_path %>

app/views/schedulers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_scheduler_path(@scheduler) %> |
<%= link_to 'Back', schedulers_path %>