config/routes.rb
Rails.application.routes.draw do
  resources :timetickets
  get 'timeticket/index'

  resources :fields
  get 'field/index'

  root to: 'gardens#index'

  resources :inventories
  resources :schedulers
  resources :gardens
  resources :bananas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server, at: '/cable'
end

app/models/garden.rb
class Garden < ApplicationRecord
  # attr_accessor :sizex, :sizey # bugs like hell when constructing instance
  has_many :bananas, dependent: :destroy
  has_one :scheduler
  CHANCESPECIAL = 4

  # after_initialize :newfield, if: :new_record?
  # after_initialize :run_scheduler, if: :new_record?
  # after_save :newfield#, :run_scheduler

  # def ini #sizex, sizey
  #   # if self.bananas.nil?
  #     newfield sizex, sizey
  #     puts "init garden"
  #   # end
  #   # run_scheduler
  # end

  after_create :newfield
  # after_initialize :run_scheduler

  def run_scheduler
    Thread.new do
      if self.scheduler.nil?
        inscribe_new_scheduler
      end
      self.scheduler.run
    end
  end

  def inscribe_new_scheduler
    puts "new scheduler for garden id #{id}"
    self.scheduler= Scheduler.create! garden_id: id
    self.save
  end

  def newfield #sizex=10, sizey=10
    # self.sizex = sizex
    # self.sizey = sizey
    # self.save
    sizex.times do |x|
      sizey.times do |y|
        chance = rand CHANCESPECIAL
        if chance == 0
          banana = Banana.create garden_id: id, specialtype: :red, ripeness: 0, posx: x, posy: y
        else
          banana = Banana.create garden_id: id, specialtype: :normal, ripeness: 0, posx: x, posy: y
        end
      end
    end
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden,:set_bananas, only: [:show, :edit, :update, :destroy]
  #todo what for?

  # GET /Gardens
  # GET /Gardens.json
  def index
    @gardens = Garden.all
  end

  # GET /Gardens/1
  # GET /Gardens/1.json
  def show
    # set_bananas
    Thread.new do
      puts "starting scheduler"
      @garden.run_scheduler
    end
  end

  # GET /Gardens/new
  def new
    @garden = Garden.new
  end

  # GET /Gardens/1/edit
  def edit
  end

  # def updategrid #todo !!! ajax/js
  #   respond_to do |format|
  #     format.js { render :js => "my_function();" }
  #   end
  # end

  # POST /Gardens
  # POST /Gardens.json
  def create
    @garden = Garden.create(garden_params)
    # @garden.newfield
    respond_to do |format|
      if @garden.save
        format.html { redirect_to @garden, notice: 'Garden was successfully created.' }
        format.json { render :show, status: :created, location: @garden }
      else
        format.html { render :new }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /Gardens/1
  # PATCH/PUT /Gardens/1.json
  def update
    respond_to do |format|
      if @garden.update(garden_params)
        format.html { redirect_to @garden, notice: 'Garden was successfully updated.' }
        format.json { render :show, status: :ok, location: @garden }
      else
        format.html { render :edit }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /Gardens/1
  # DELETE /Gardens/1.json
  def destroy
    @garden.destroy
    respond_to do |format|
      format.html { redirect_to gardens_url, notice: 'Garden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_garden
      @garden = Garden.find(params[:id])
    end

    def set_bananas
      @bananas = @garden.bananas
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def garden_params
      params.require(:garden).permit(:sizex, :sizey)
    end
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/views/gardens/_form.html.erb
<%= form_with(model: garden, local: true) do |form| %>
  <% if garden.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(garden.errors.count, "error") %> prohibited this garden from being saved:</h2>

      <ul>
      <% garden.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sizex %>
    <%= form.number_field :sizex, id: :garden_sizex %>
  </div>

  <div class="field">
    <%= form.label :sizey %>
    <%= form.number_field :sizey, id: :garden_sizey %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<h1>Editing Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Show', @garden %> |
<%= link_to 'Back', gardens_path %>

app/views/gardens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gardens</h1>

<table>
  <thead>
    <tr>
      <th>Sizex</th>
      <th>Sizey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%# if @gardens.nil? %>
    <%# #todo render something .. %>
    <%# else %>
    <% @gardens.each do |garden| %>
      <tr>
        <td><%= garden.sizex %></td>
        <td><%= garden.sizey %></td>
        <td><%= link_to 'Show', garden %></td>
        <td><%= link_to 'Edit', edit_garden_path(garden) %></td>
        <td><%= link_to 'Destroy', garden, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%# end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garden', new_garden_path %>

app/views/gardens/new.html.erb
<h1>New Garden</h1>

<%= render 'form', garden: @garden %>

<%= link_to 'Back', gardens_path %>

app/views/gardens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sizex:</strong>
  <%= @garden.sizex %>
</p>

<p>
  <strong>Sizey:</strong>
  <%= @garden.sizey %>
</p>
<table>
  <tbody>
  <% rowid = 0%>
  <% @bananas.in_groups_of(@garden.sizex) do |rows| %>
    <tr>
      <% rowid += 1%>
      <% colid = 0%>
      <% rows.each do |b| %>
          <% colid += 1%>
          <% tostring = "#{rowid}-#{colid}"%>
        <td id="<%= tostring %>" class="ban">
          <%= imghelper b.ripeness %>
        </td>
      <% end %>
    </tr>
  <% end%>
  </tbody>
</table>



  <%= link_to 'Edit', edit_garden_path(@garden) %> |
  <%= link_to 'Back', gardens_path %>

  <%# if @garden.bananas then @garden.bananas.each do |banana| %>
<%#= svg_embed "banana.svg" %>
<!--<p>hello</p>-->
<!--    todo cross reference mit belongs_to funktioniert hier-->
  <%# end end %>

app/views/gardens/updategrid.js.erb
function fire(){
alert("got function passing")
}

<!--#todo ??-->